// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify the MCP connection is live.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-aratutec-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_aratutec_info_default = defineTool2({
  name: "get_aratutec_info",
  title: "Get Aratutec info",
  description: "Returns key facts about Aratutec: the OpenAI-compatible AI API built and operated by Pedro Murilo Gomes, including base URL, capabilities, and links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            product: "Aratutec",
            author: "Pedro Murilo Maciel Gomes",
            role: "Software & AI Developer (mid-level)",
            api_base_url: "https://aratutec.org/v1",
            docs_url: "https://aratutec.org/docs",
            site: "https://aratutec.org",
            capabilities: [
              "OpenAI-compatible chat completions",
              "Vision (image inputs)",
              "SSE streaming",
              "Self-hosted inference",
              "Multi-tenant backend"
            ],
            infra: [
              "Cloudflare Tunnel",
              "Proxmox / Linux",
              "FastAPI backend",
              "Vue / Nuxt frontend",
              "Supabase auth & data"
            ],
            contact: {
              email: "pedrogomes600@hotmail.com",
              github: "https://github.com/PedroMMGomes",
              linkedin: "https://linkedin.com/in/pedrogomes600"
            }
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "aratutec-mcp",
  title: "Aratutec MCP",
  version: "0.1.0",
  instructions: "Tools for the Aratutec portfolio site. Use `get_aratutec_info` to fetch facts about the Aratutec AI API and its author Pedro Murilo Gomes. Use `echo` to verify connectivity.",
  tools: [echo_default, get_aratutec_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
